import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ExpenseDashboard } from "@/features/expenses/ExpenseDashboard";
import { CATEGORY_ICON_OPTIONS, categoryIconGlyph, type ExpenseCategorySetting } from "@/features/expenses/category-settings";
import { ExpenseFilterControls } from "@/features/expenses/ExpenseFilterControls";
import { groupExpensesByCategory, monthLabel, percentOf, previousMonthKey } from "@/features/expenses/analytics";
import { expensePeriodMonthKey, filterExpenseDimensions, filterExpensePeriod, normalizeExpenseFilters, sortExpensesNewestFirst } from "@/features/expenses/filters";
import { InvitePanel } from "@/features/live/InvitePanel";
import { ConfirmSubmitButton } from "@/features/live/ConfirmSubmitButton";
import { RealtimeGoalSync } from "@/features/live/RealtimeGoalSync";
import { FinancialOverview } from "@/features/live/FinancialOverview";
import { AddExpenseForm, AddSavingForm } from "@/features/live/ManualEntryForms";
import { PullToRefresh } from "@/features/live/PullToRefresh";
import { LanguageSwitcher } from "@/features/preferences/LanguageSwitcher";
import { PreferenceSync } from "@/features/preferences/PreferenceSync";
import { SavingsDashboard } from "@/features/savings/SavingsDashboard";
import { participantNetSavings, sharePercent } from "@/features/savings/analytics";
import { convertMinorUnits, formatCrossRate, SUPPORTED_CURRENCIES, type FxRateSnapshot } from "@/lib/fx";
import { getOfficialFxRates } from "@/lib/fx/server";
import type { LiveAuditEntry, LiveParticipant } from "@/features/live/types";
import { localeTag, systemCategoryName, tr, type AppLocale } from "@/lib/i18n";
import { resolveAuthenticatedLocale } from "@/lib/i18n/server";
import {
  calculateActualSaved,
  calculateIncludedExpenses,
  calculateProgressPercent,
  calculateRemaining,
  formatMoney,
  signedSavingsAmount,
  visualProgressPercent,
  type CurrencyCode,
  type SavingsType,
} from "@/lib/money";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile, getGoalSnapshot, listExpenseCategorySettings, listGoalInvitations } from "@/server/goals/repository";
import {
  archiveExpenseCategoryAction,
  archiveGoalAction,
  createExpenseCategoryAction,
  removeMemberAction,
  resetSystemCategoryOverrideAction,
  restoreExpenseCategoryAction,
  restoreExpenseAction,
  restoreSavingAction,
  revokeInvitationAction,
  updateExpenseCategoryAction,
  updateGoalAction,
} from "./actions";

function savingLabels(locale: AppLocale): Record<SavingsType, string> {
  return {
    contribution: tr(locale, "Пополнение", "Contribution"),
    interest: tr(locale, "Проценты", "Interest"),
    withdrawal: tr(locale, "Снятие", "Withdrawal"),
    fee: tr(locale, "Комиссия", "Fee"),
    adjustment_plus: tr(locale, "Корректировка +", "Adjustment +"),
    adjustment_minus: tr(locale, "Корректировка −", "Adjustment −"),
  };
}

function dateLabel(value: string, locale: AppLocale): string {
  return new Intl.DateTimeFormat(localeTag(locale), { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));
}
function dateTimeLabel(value: string, locale: AppLocale): string {
  return new Intl.DateTimeFormat(localeTag(locale), { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}
function minorInput(value: bigint): string { const whole = value / 100n; const fraction = value % 100n; return fraction === 0n ? whole.toString() : `${whole}.${fraction.toString().padStart(2, "0")}`; }
function participantName(participants: LiveParticipant[], id: string, locale: AppLocale): string { return participants.find((person) => person.id === id)?.name ?? tr(locale, "Участник", "Member"); }
function auditLabel(entry: LiveAuditEntry, locale: AppLocale): string {
  const entity = entry.entityType;
  if (entity === "savings_transactions") { if (entry.action === "create") return tr(locale,"Добавлено накопление","Savings transaction added"); if (entry.action === "soft_delete") return tr(locale,"Удалено накопление","Savings transaction deleted"); if (entry.action === "restore") return tr(locale,"Восстановлено накопление","Savings transaction restored"); return tr(locale,"Изменено накопление","Savings transaction updated"); }
  if (entity === "expenses") { if (entry.action === "create") return tr(locale,"Добавлен расход","Expense added"); if (entry.action === "soft_delete") return tr(locale,"Удалён расход","Expense deleted"); if (entry.action === "restore") return tr(locale,"Восстановлен расход","Expense restored"); return tr(locale,"Изменён расход","Expense updated"); }
  if (entity === "goal_member") { if (entry.action === "join") return tr(locale,"Участник присоединился","Member joined"); if (entry.action === "remove_member") return tr(locale,"Участник удалён из цели","Member removed"); return tr(locale,"Изменено участие в цели","Membership updated"); }
  if (entity === "goal_invitation") return entry.action === "invite" ? tr(locale,"Создано приглашение","Invitation created") : tr(locale,"Изменено приглашение","Invitation updated");
  if (entity === "expense_category") return entry.action === "create" ? tr(locale,"Создана категория расходов","Expense category created") : tr(locale,"Изменена категория расходов","Expense category updated");
  if (entity === "goal") { if (entry.action === "archive") return tr(locale,"Цель архивирована","Goal archived"); if (entry.action === "create") return tr(locale,"Цель создана","Goal created"); return tr(locale,"Изменены параметры цели","Goal settings updated"); }
  return tr(locale,"Изменены данные цели","Goal data updated");
}

const iconLabelsEn: Record<string, string> = {
  "shopping-basket":"Basket", utensils:"Food", car:"Transport", house:"Home", "heart-pulse":"Health", sparkles:"Care", shirt:"Clothing", wifi:"Connectivity", ticket:"Entertainment", "book-open":"Education", plane:"Travel", "paw-print":"Pets", gift:"Gifts", "receipt-text":"Receipt", "arrow-left-right":"Transfers", banknote:"Cash", gamepad:"Games", dumbbell:"Sport", music:"Music", coffee:"Coffee", "circle-ellipsis":"Other", "circle-help":"Review", circle:"Circle",
};
function iconOptionLabel(value: string, fallback: string, locale: AppLocale) { return locale === "en" ? iconLabelsEn[value] ?? fallback : fallback; }

export default async function GoalPage({ params, searchParams }: { params: Promise<{ goalId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { goalId } = await params; const query = await searchParams; const supabase = await createClient(); const { data } = await supabase.auth.getClaims(); const userId = data?.claims?.sub;
  if (!userId) redirect(`/login?next=${encodeURIComponent(`/goals/${goalId}`)}`);
  const [snapshot, profile] = await Promise.all([getGoalSnapshot(goalId, userId), getCurrentProfile(userId)]);
  if (!snapshot) notFound(); if (!profile?.displayName) redirect(`/profile/setup?next=${encodeURIComponent(`/goals/${goalId}`)}`);
  const locale = await resolveAuthenticatedLocale(profile.locale); const numberLocale = localeTag(locale); const labels = savingLabels(locale); const readOnly = snapshot.goal.status === "archived";
  const [rawCategorySettings, invitations] = await Promise.all([listExpenseCategorySettings(goalId), snapshot.goal.role === "owner" && !readOnly ? listGoalInvitations(goalId) : Promise.resolve([])]);
  const categorySettings = rawCategorySettings.map((category) => ({ ...category, name: category.isSystem ? systemCategoryName(category.key, category.name, locale) : category.name }));
  const categoryNameById = new Map(categorySettings.map((category) => [category.id, category.name]));
  const localizedExpenses = snapshot.expenses.map((expense) => ({ ...expense, categoryName: categoryNameById.get(expense.categoryId) ?? expense.categoryName }));
  const localizedDeletedExpenses = snapshot.deletedExpenses.map((expense) => ({ ...expense, categoryName: categoryNameById.get(expense.categoryId) ?? expense.categoryName }));
  const categories = categorySettings.filter((category) => category.archivedAt === null); const expenseCategoryIds = new Set(localizedExpenses.map((expense) => expense.categoryId)); const filterCategories = categorySettings.filter((category) => category.archivedAt === null || expenseCategoryIds.has(category.id));
  const foreignCurrencies = Array.from(new Set(snapshot.savings.filter((item) => !item.deletedAt && item.currencyCode !== snapshot.goal.currencyCode).map((item) => item.currencyCode)));
  const fxRates = foreignCurrencies.length ? await getOfficialFxRates() : null;
  const calculationSavings = snapshot.savings.map((item) => {
    const converted = convertMinorUnits(item.amountMinor, item.currencyCode, snapshot.goal.currencyCode, fxRates);
    return { ...item, amountMinor: converted ?? 0n, currencyCode: snapshot.goal.currencyCode };
  });
  const fxIncomplete = foreignCurrencies.length > 0 && fxRates === null;
  const actualSaved = calculateActualSaved(calculationSavings); const remaining = calculateRemaining(snapshot.goal.targetAmountMinor, actualSaved); const progress = calculateProgressPercent(snapshot.goal.targetAmountMinor, actualSaved); const expenseFilters = normalizeExpenseFilters(query); const now = new Date();
  const dimensionFilteredExpenses = filterExpenseDimensions(localizedExpenses, expenseFilters); const filteredExpenses = sortExpensesNewestFirst(filterExpensePeriod(dimensionFilteredExpenses, expenseFilters.period, now, snapshot.viewerTimeZone)); const periodMonthKey = expensePeriodMonthKey(expenseFilters.period, now, snapshot.viewerTimeZone); const periodLabel = periodMonthKey ? monthLabel(periodMonthKey, numberLocale) : tr(locale,"За всё время","All time"); const previousPeriodKey = periodMonthKey ? previousMonthKey(periodMonthKey) : null; const previousPeriodExpenses = previousPeriodKey ? dimensionFilteredExpenses.filter((item) => item.transactionDate.startsWith(previousPeriodKey)) : []; const totalExpenses = calculateIncludedExpenses(filteredExpenses);
  const comparison = periodMonthKey && previousPeriodKey ? { previousLabel: monthLabel(previousPeriodKey, numberLocale), previousAmountMinor: calculateIncludedExpenses(previousPeriodExpenses), currentLabel: monthLabel(periodMonthKey, numberLocale), currentAmountMinor: totalExpenses } : null;
  const currentMonthKey = expensePeriodMonthKey("current", now, snapshot.viewerTimeZone)!; const previousMonth = previousMonthKey(currentMonthKey); const currentMonthExpenses = sortExpensesNewestFirst(filterExpensePeriod(localizedExpenses, "current", now, snapshot.viewerTimeZone)); const currentMonthExpenseTotal = calculateIncludedExpenses(currentMonthExpenses); const currentMonthExpenseGroups = groupExpensesByCategory(currentMonthExpenses); const categoryColorById = new Map(categorySettings.map((category) => [category.id, category.color]));
  const overviewExpenseGradient = currentMonthExpenseGroups.length ? currentMonthExpenseGroups.map((group,index)=>{const before=currentMonthExpenseGroups.slice(0,index).reduce((sum,item)=>sum+percentOf(item.amountMinor,currentMonthExpenseTotal),0);const after=before+percentOf(group.amountMinor,currentMonthExpenseTotal);const color=categoryColorById.get(group.categoryId)??["#6F806A","#C88F87","#C2A15C","#8F9B88"][index%4];return `${color} ${before}% ${after}%`;}).join(", ") : "var(--line) 0 100%";
  const hasCustomExpenseFilters = expenseFilters.period !== "current" || expenseFilters.participantId !== "all" || expenseFilters.categoryId !== "all" || expenseFilters.source !== "all" || expenseFilters.status !== "all"; const updateGoal = updateGoalAction.bind(null, goalId); const hasDeleted = snapshot.deletedSavings.length > 0 || localizedDeletedExpenses.length > 0; const money=(value:bigint)=>formatMoney(value,snapshot.goal.currencyCode,numberLocale); const defaultTransactionDate=now.toISOString().slice(0,10);
  const netByCurrency = new Map<CurrencyCode, bigint>();
  for (const item of snapshot.savings) { if (item.deletedAt) continue; netByCurrency.set(item.currencyCode, (netByCurrency.get(item.currencyCode) ?? 0n) + signedSavingsAmount(item)); }
  const savingCurrencyBalances = SUPPORTED_CURRENCIES.map((currency) => ({ currency, amountMinor: netByCurrency.get(currency) ?? 0n }));
  const fxBalances = savingCurrencyBalances.filter((item) => item.amountMinor !== 0n).map((item) => ({ ...item, convertedMinor: convertMinorUnits(item.amountMinor, item.currency, snapshot.goal.currencyCode, fxRates) }));

  return <div className="live-shell"><PreferenceSync locale={locale} theme={profile.theme} font={profile.font} /><RealtimeGoalSync goalId={goalId} />
    <header className="live-topbar goal-topbar"><Link href="/" className="back-link">← {tr(locale,"Мои цели","My goals")}</Link><div className="topbar-actions"><LanguageSwitcher locale={locale} /><Link className="text-button topbar-link" href="/support">{tr(locale,"Помощь","Help")}</Link><Link className="text-button topbar-link" href="/profile">{tr(locale,"Профиль","Profile")}</Link><form action="/auth/signout" method="post"><button className="text-button" type="submit">{tr(locale,"Выйти","Sign out")}</button></form></div></header>
    <PullToRefresh locale={locale}><main className="live-main"><section className="page-section compact-page">
      <div className="overview-heading-row simplified-heading-row"><div className="page-heading simplified-heading"><span className="eyebrow">{tr(locale,"до","by")} {dateLabel(snapshot.goal.targetDate,locale)}</span><h1>{snapshot.goal.title}</h1></div><span className="role-chip">{readOnly?tr(locale,"Архив · только чтение","Archived · read only"):snapshot.goal.role==="owner"?tr(locale,"Владелец","Owner"):tr(locale,"Участник","Member")}</span></div>
      {typeof query.error === "string" && query.error && <p className="form-error" role="alert">{tr(locale,"Не удалось выполнить действие. Данные не были изменены.","Could not complete the action. No data was changed.")}</p>}
      <FinancialOverview locale={locale} initialOpen={query.panel==="savings"?"savings":hasCustomExpenseFilters?"expenses":null}
        savingsSummary={<div className="overview-card-content savings-summary-content"><div className="overview-card-topline"><div><span className="eyebrow">{tr(locale,"Накопления","Savings")}</span><strong className="overview-card-amount">{money(actualSaved)}</strong></div><span className="overview-percent">{progress.toFixed(1)}%</span></div><div className="overview-card-subline">{tr(locale,"из","of")} {money(snapshot.goal.targetAmountMinor)}</div><div className="progress-track overview-progress" aria-hidden="true"><span style={{width:`${visualProgressPercent(progress)}%`}} /></div><div className="overview-card-footer"><span>{tr(locale,"Осталось","Remaining")} {money(remaining)}</span><span>{tr(locale,"Подробнее","Details")}</span></div></div>}
        expensesSummary={<div className="overview-card-content expenses-summary-content"><div className="overview-expense-copy"><span className="eyebrow">{tr(locale,"Расходы за месяц","Monthly expenses")}</span><strong className="overview-card-amount">{money(currentMonthExpenseTotal)}</strong><span className="overview-card-subline">{monthLabel(currentMonthKey,numberLocale)}</span><span className="overview-card-footer-inline">{tr(locale,"Подробнее","Details")}</span></div><div className="overview-mini-donut" style={{background:`conic-gradient(${overviewExpenseGradient})`}} aria-hidden="true"><span /></div></div>}
        savingsDetails={<section className="overview-detail-section"><div className="section-title compact-detail-title"><div><span className="eyebrow">{tr(locale,"Подробно","Details")}</span><h2>{tr(locale,"Накопления","Savings")}</h2></div><strong>{money(actualSaved)}</strong></div><div className="detail-actions-row detail-actions-primary">{!readOnly&&<details className="action-details compact-action-details prominent-action-details" id="add-saving" open={query.add==="saving"}><summary>＋ {tr(locale,"Добавить накопление","Add savings")}</summary><AddSavingForm goalId={goalId} participants={snapshot.participants} viewerUserId={userId} goalCurrency={snapshot.goal.currencyCode} currencyBalances={savingCurrencyBalances} locale={locale} defaultDate={defaultTransactionDate} /></details>}{!readOnly&&<Link className="secondary-button compact-link-button" href={`/goals/${goalId}/import?kind=savings`}>{tr(locale,"Импортировать файл","Import file")}</Link>}</div>{foreignCurrencies.length>0&&<FxBreakdown balances={fxBalances} targetCurrency={snapshot.goal.currencyCode} fxRates={fxRates} locale={locale} />}{fxIncomplete&&<p className="form-error fx-warning" role="status">{tr(locale,"Курс НБК временно недоступен. Валютные накопления сейчас не включены в общий прогресс; исходные суммы сохранены без изменений.","The NBK rate is temporarily unavailable. Foreign-currency savings are not included in the total right now; original amounts remain unchanged.")}</p>}<SavingsDashboard locale={locale} savings={calculationSavings} actualSavedMinor={actualSaved} targetAmountMinor={snapshot.goal.targetAmountMinor} targetDate={snapshot.goal.targetDate} currencyCode={snapshot.goal.currencyCode} viewerTimeZone={snapshot.viewerTimeZone} now={now} /><Link className="history-nav-row" href={`/goals/${goalId}/savings`}><span><strong>{tr(locale,"История пополнений","Savings history")}</strong><small>{tr(locale,`Всего: ${snapshot.savings.length}`,`Total: ${snapshot.savings.length}`)}</small></span><span className="history-nav-chevron" aria-hidden="true">→</span></Link></section>}
        expensesDetails={<section className="overview-detail-section"><div className="section-title compact-detail-title"><div><span className="eyebrow">{tr(locale,"Подробно","Details")}</span><h2>{tr(locale,"Расходы","Expenses")}</h2></div><strong>{money(totalExpenses)}</strong></div><div className="detail-actions-row detail-actions-primary">{!readOnly&&<details className="action-details compact-action-details"><summary>+ {tr(locale,"Добавить расход","Add expense")}</summary><AddExpenseForm goalId={goalId} participants={snapshot.participants} categories={categories} viewerUserId={userId} locale={locale} defaultDate={defaultTransactionDate} /></details>}{!readOnly&&<Link className="secondary-button compact-link-button" href={`/goals/${goalId}/import?kind=expenses`}>{tr(locale,"Импортировать файл","Import file")}</Link>}</div><details className="expense-filter-details" open={hasCustomExpenseFilters}><summary>{tr(locale,"Фильтры","Filters")} <span>{periodLabel}</span></summary><ExpenseFilterControls locale={locale} goalId={goalId} initialFilters={expenseFilters} currentMonthLabel={monthLabel(currentMonthKey,numberLocale)} previousMonthLabel={monthLabel(previousMonth,numberLocale)} participants={snapshot.participants.map((person)=>({id:person.id,name:person.name}))} categories={filterCategories.map((category)=>({id:category.id,name:`${category.name}${category.archivedAt?tr(locale," (архив)"," (archived)"):""}`}))} /></details><ExpenseDashboard locale={locale} expenses={filteredExpenses} categories={categorySettings} currencyCode={snapshot.goal.currencyCode} periodLabel={periodLabel} comparison={comparison} /><CategoryManager locale={locale} goalId={goalId} categories={categorySettings} readOnly={readOnly} /><Link className="history-nav-row" href={`/goals/${goalId}/expenses`}><span><strong>{tr(locale,"История расходов","Expense history")}</strong><small>{tr(locale,`Всего: ${snapshot.expenses.length}`,`Total: ${snapshot.expenses.length}`)}</small></span><span className="history-nav-chevron" aria-hidden="true">→</span></Link><p className="invariant-note detail-invariant">{tr(locale,"Расходы не уменьшают сумму накоплений и прогресс цели.","Expenses never reduce savings or goal progress.")}</p></section>} />

      <section className="live-section overview-members-section" id="members"><div className="section-title"><div><span className="eyebrow">{tr(locale,"Совместная цель","Shared goal")}</span><h2>{tr(locale,"Участники","Members")}</h2></div><span className="muted">{snapshot.participants.length}</span></div><div className="member-cards">{snapshot.participants.map((person)=>{const contribution=participantNetSavings(calculationSavings,person.id);const share=sharePercent(contribution,actualSaved);return <div className="member-card participant-contribution-card" key={person.id}><div className="avatar">{person.name.slice(0,1).toUpperCase()}</div><div className="participant-contribution-info"><div className="participant-name-line"><strong>{person.name}</strong><span>{person.role==="owner"?tr(locale,"Владелец","Owner"):tr(locale,"Участник","Member")}</span></div><div className="participant-share-track" aria-hidden="true"><span style={{width:`${Math.min(100,Math.max(0,share))}%`}} /></div><small>{actualSaved>0n&&contribution>0n?tr(locale,`${share.toFixed(0)}% общей суммы`,`${share.toFixed(0)}% of total`):tr(locale,"Пока без положительного вклада","No positive contribution yet")}</small></div><strong>{money(contribution)}</strong>{snapshot.goal.role==="owner"&&!readOnly&&person.role==="member"&&<form action={removeMemberAction.bind(null,goalId,person.id)}><ConfirmSubmitButton className="danger-text-button" message={tr(locale,"Удалить участника из этой цели? Его прежние операции и авторство сохранятся.","Remove this member from the goal? Their previous transactions and authorship will remain.")}>{tr(locale,"Удалить","Remove")}</ConfirmSubmitButton></form>}</div>;})}</div>
        {snapshot.goal.role==="owner"&&!readOnly&&<details className="management-details"><summary>{tr(locale,"Управление участниками","Manage members")}</summary><div className="owner-tools"><InvitePanel goalId={goalId} locale={locale} />{invitations.length>0&&<div className="active-invites"><span className="eyebrow">{tr(locale,"Активные ссылки","Active links")}</span>{invitations.map((invite)=><div key={invite.id}><span>{tr(locale,"до","until")} {new Intl.DateTimeFormat(numberLocale,{dateStyle:"medium"}).format(new Date(invite.expiresAt))}</span><form action={revokeInvitationAction.bind(null,goalId,invite.id)}><ConfirmSubmitButton className="text-button" message={tr(locale,"Отозвать эту ссылку-приглашение?","Revoke this invitation link?")}>{tr(locale,"Отозвать","Revoke")}</ConfirmSubmitButton></form></div>)}</div>}</div></details>}
      </section>

      <section className="overview-secondary-section" id="activity"><details className="collapsible-overview-section"><summary><span>{tr(locale,"История","History")}</span><small>{snapshot.audit.length?tr(locale,`${Math.min(snapshot.audit.length,12)} последних действий`,`${Math.min(snapshot.audit.length,12)} recent actions`):tr(locale,"Пока пусто","Empty")}</small></summary><div className="collapsible-overview-body"><div className="activity-list">{snapshot.audit.slice(0,12).map((entry)=><div className="activity-row" key={entry.id}><span className="activity-dot" aria-hidden="true" /><div><strong>{auditLabel(entry,locale)}</strong><span>{participantName(snapshot.participants,entry.actorUserId,locale)} · {dateTimeLabel(entry.createdAt,locale)}</span></div></div>)}{!snapshot.audit.length&&<p className="empty-text">{tr(locale,"История пока пуста.","History is empty.")}</p>}</div></div></details></section>

      {hasDeleted&&!readOnly&&<section className="overview-secondary-section"><details className="collapsible-overview-section"><summary><span>{tr(locale,"Недавно удалённые операции","Recently deleted transactions")}</span><small>{snapshot.deletedSavings.length+localizedDeletedExpenses.length}</small></summary><div className="collapsible-overview-body deleted-list">{snapshot.deletedSavings.map((item)=><div className="deleted-row" key={item.id}><div><strong>{labels[item.type]}</strong><span>{dateLabel(item.transactionDate,locale)} · {formatMoney(item.amountMinor,item.currencyCode,numberLocale)}</span></div><form action={restoreSavingAction.bind(null,goalId,item.id)}><button className="text-button" type="submit">{tr(locale,"Восстановить","Restore")}</button></form></div>)}{localizedDeletedExpenses.map((item)=><div className="deleted-row" key={item.id}><div><strong>{item.merchantNormalized}</strong><span>{dateLabel(item.transactionDate,locale)} · {money(item.amountMinor)}</span></div><form action={restoreExpenseAction.bind(null,goalId,item.id)}><button className="text-button" type="submit">{tr(locale,"Восстановить","Restore")}</button></form></div>)}</div></details></section>}

      <section className="overview-secondary-section settings-section"><details className="collapsible-overview-section"><summary><span>{tr(locale,"Настройки цели","Goal settings")}</span><small>{snapshot.goal.role==="owner"?tr(locale,"Управление","Manage"):tr(locale,"Параметры","Settings")}</small></summary><div className="collapsible-overview-body settings-stack">{!readOnly&&<form className="compact-form" action={updateGoal}><label className="wide">{tr(locale,"Название","Name")}<input name="title" maxLength={120} required defaultValue={snapshot.goal.title} /></label><label>{tr(locale,"Сумма цели","Goal amount")}<input name="targetAmount" inputMode="decimal" required defaultValue={minorInput(snapshot.goal.targetAmountMinor)} /></label><label>{tr(locale,"Срок","Deadline")}<input name="targetDate" type="date" required defaultValue={snapshot.goal.targetDate} /></label><div className="wide settings-note">{tr(locale,"Валюта","Currency")}: <strong>{snapshot.goal.currencyCode}</strong>. {tr(locale,"После первой финансовой операции она не меняется.","It cannot be changed after the first financial transaction.")}</div><button className="primary-button" type="submit">{tr(locale,"Сохранить параметры","Save settings")}</button></form>}{readOnly&&<p className="empty-text">{tr(locale,"Архивная цель доступна только для чтения.","Archived goals are read-only.")}</p>}{snapshot.goal.role==="owner"&&!readOnly&&<div className="danger-zone"><div><strong>{tr(locale,"Архивировать цель","Archive goal")}</strong><p>{tr(locale,"Цель останется доступной для просмотра, но финансовые и административные изменения будут заблокированы.","The goal will remain visible but financial and administrative changes will be blocked.")}</p></div><form action={archiveGoalAction.bind(null,goalId)}><ConfirmSubmitButton className="danger-button" message={tr(locale,"Архивировать цель? После этого она станет доступна только для чтения.","Archive this goal? It will become read-only.")}>{tr(locale,"Архивировать","Archive")}</ConfirmSubmitButton></form></div>}</div></details></section>
    </section></main></PullToRefresh>
  </div>;
}

function currencyName(currency: CurrencyCode, locale: AppLocale): string {
  const names: Record<CurrencyCode, [string, string]> = {
    KZT: ["Тенге", "Tenge"], EUR: ["Евро", "Euro"], USD: ["Доллар США", "US dollar"], RUB: ["Российский рубль", "Russian ruble"],
  };
  return locale === "en" ? names[currency][1] : names[currency][0];
}

function FxBreakdown({ balances, targetCurrency, fxRates, locale }: { balances: { currency: CurrencyCode; amountMinor: bigint; convertedMinor: bigint | null }[]; targetCurrency: CurrencyCode; fxRates: FxRateSnapshot | null; locale: AppLocale }) {
  const numberLocale = localeTag(locale);
  return <section className="panel fx-breakdown"><div className="fx-breakdown-heading"><div><span className="eyebrow">{tr(locale,"Валюты накоплений","Savings currencies")}</span><h3>{tr(locale,"Что входит в общую сумму","What makes up the total")}</h3></div>{fxRates&&<small>{tr(locale,"Курс НБК на","NBK rate for")} {dateLabel(fxRates.effectiveDate,locale)}</small>}</div><div className="fx-balance-list">{balances.map((item)=><div className="fx-balance-row" key={item.currency}><div><strong>{formatMoney(item.amountMinor,item.currency,numberLocale)}</strong><span>{currencyName(item.currency,locale)}</span></div><div>{item.currency===targetCurrency?<strong>{formatMoney(item.amountMinor,targetCurrency,numberLocale)}</strong>:item.convertedMinor!==null?<><strong>≈ {formatMoney(item.convertedMinor,targetCurrency,numberLocale)}</strong>{fxRates&&<small>1 {item.currency} ≈ {formatCrossRate(item.currency,targetCurrency,fxRates,numberLocale)} {targetCurrency}</small>}</>:<strong>—</strong>}</div></div>)}</div>{fxRates&&<p className="settings-note">{tr(locale,"Исходные суммы хранятся в своей валюте. Для прогресса цели они пересчитываются по текущему официальному курсу Национального Банка Казахстана.","Original amounts stay in their own currencies. For goal progress they are converted using the current official National Bank of Kazakhstan rate.")}</p>}</section>;
}

function CategoryManager({ goalId, categories, readOnly, locale }: { goalId:string; categories:ExpenseCategorySetting[]; readOnly:boolean; locale:AppLocale }) {
  const activeCustom=categories.filter((c)=>!c.isSystem&&c.archivedAt===null); const system=categories.filter((c)=>c.isSystem&&c.archivedAt===null); const archivedCustom=categories.filter((c)=>!c.isSystem&&c.archivedAt!==null);
  return <details className="management-details category-management"><summary>{tr(locale,"Категории расходов","Expense categories")} <span>{system.length+activeCustom.length}</span></summary><div className="category-manager-stack"><p className="settings-note">{tr(locale,"Категории используются в расходах, импорте и диаграмме. Системные категории нельзя удалить или переименовать, но для этой цели можно изменить их цвет, значок и правило «необязательный по умолчанию».","Categories are used for expenses, imports and charts. System categories cannot be deleted or renamed, but their color, icon and default discretionary setting can be customized for this goal.")}</p>
    {!readOnly&&<details className="action-details category-create-details"><summary>+ {tr(locale,"Создать свою категорию","Create custom category")}</summary><form className="compact-form category-form" action={createExpenseCategoryAction.bind(null,goalId)}><label className="wide">{tr(locale,"Название","Name")}<input name="name" required maxLength={60} placeholder={tr(locale,"Например, Хобби","For example, Hobbies")} /></label><label>{tr(locale,"Значок","Icon")}<select name="icon" defaultValue="circle">{CATEGORY_ICON_OPTIONS.map((o)=><option value={o.value} key={o.value}>{o.glyph} {iconOptionLabel(o.value,o.label,locale)}</option>)}</select></label><label>{tr(locale,"Цвет","Color")}<input className="category-color-input" type="color" name="color" defaultValue="#6F806A" aria-label={tr(locale,"Цвет категории","Category color")} /></label><label className="checkbox-label wide"><input type="checkbox" name="defaultDiscretionary" /><span><strong>{tr(locale,"Необязательный расход по умолчанию","Discretionary by default")}</strong><small>{tr(locale,"Новые импортированные операции этой категории будут попадать в «Можно было отложить». Это всегда можно изменить у конкретного расхода.","New imported transactions in this category will count toward “Could have saved”. You can always change an individual expense.")}</small></span></label><button className="primary-button" type="submit">{tr(locale,"Создать категорию","Create category")}</button></form></details>}
    {activeCustom.length>0&&<section className="category-group" aria-labelledby="custom-categories-heading"><div className="category-group-heading"><strong id="custom-categories-heading">{tr(locale,"Мои категории","My categories")}</strong><span>{activeCustom.length}</span></div><div className="category-settings-list">{activeCustom.map((c)=><CategorySettingRow key={c.id} goalId={goalId} category={c} readOnly={readOnly} locale={locale} />)}</div></section>}
    <section className="category-group" aria-labelledby="system-categories-heading"><div className="category-group-heading"><strong id="system-categories-heading">{tr(locale,"Системные категории","System categories")}</strong><span>{system.length}</span></div><div className="category-settings-list">{system.map((c)=><CategorySettingRow key={c.id} goalId={goalId} category={c} readOnly={readOnly} locale={locale} />)}</div></section>
    {archivedCustom.length>0&&<details className="archived-category-details"><summary>{tr(locale,"Архивные категории","Archived categories")} <span>{archivedCustom.length}</span></summary><div className="archived-category-list">{archivedCustom.map((c)=><div className="archived-category-row" key={c.id}><div className="category-name-cell"><span className="category-swatch" style={{backgroundColor:c.color}}>{categoryIconGlyph(c.icon)}</span><div><strong>{c.name}</strong><span>{tr(locale,"Не предлагается для новых расходов","Not offered for new expenses")}</span></div></div>{!readOnly&&<form action={restoreExpenseCategoryAction.bind(null,goalId,c.id)}><button className="text-button" type="submit">{tr(locale,"Восстановить","Restore")}</button></form>}</div>)}</div></details>}
  </div></details>;
}

function CategorySettingRow({ goalId, category, readOnly, locale }: { goalId:string; category:ExpenseCategorySetting; readOnly:boolean; locale:AppLocale }) {
  const update=updateExpenseCategoryAction.bind(null,goalId,category.id);
  return <details className="category-setting-row"><summary><span className="category-swatch" style={{backgroundColor:category.color}}>{categoryIconGlyph(category.icon)}</span><span className="category-setting-name"><strong>{category.name}</strong><small>{category.isSystem?tr(locale,"Системная","System"):tr(locale,"Своя","Custom")}{category.hasOverride?tr(locale," · изменена для этой цели"," · customized for this goal"):""}</small></span><span className="category-default-chip">{category.defaultDiscretionary?tr(locale,"необязательная","discretionary"):tr(locale,"обычная","standard")}</span></summary><div className="category-setting-panel">{readOnly?<p className="empty-text">{tr(locale,"Архивная цель доступна только для чтения.","Archived goals are read-only.")}</p>:<><form className="compact-form category-form" action={update}>{category.isSystem?<div className="wide settings-note">{tr(locale,"Название системной категории фиксировано:","System category name is fixed:")} <strong>{category.name}</strong>.</div>:<label className="wide">{tr(locale,"Название","Name")}<input name="name" required maxLength={60} defaultValue={category.name} /></label>}<label>{tr(locale,"Значок","Icon")}<select name="icon" defaultValue={category.icon??"circle"}>{CATEGORY_ICON_OPTIONS.map((o)=><option value={o.value} key={o.value}>{o.glyph} {iconOptionLabel(o.value,o.label,locale)}</option>)}</select></label><label>{tr(locale,"Цвет","Color")}<input className="category-color-input" type="color" name="color" defaultValue={category.color} aria-label={`${tr(locale,"Цвет категории","Category color")} ${category.name}`} /></label><label className="checkbox-label wide"><input type="checkbox" name="defaultDiscretionary" defaultChecked={category.defaultDiscretionary} /><span><strong>{tr(locale,"Необязательный расход по умолчанию","Discretionary by default")}</strong><small>{tr(locale,"Используется как подсказка при импорте. Отдельную операцию всё равно можно изменить вручную.","Used as an import suggestion. Individual expenses can still be changed manually.")}</small></span></label><button className="primary-button" type="submit">{tr(locale,"Сохранить","Save")}</button></form><div className="category-secondary-actions">{category.isSystem&&category.hasOverride&&<form action={resetSystemCategoryOverrideAction.bind(null,goalId,category.id)}><button className="text-button" type="submit">{tr(locale,"Сбросить оформление","Reset appearance")}</button></form>}{!category.isSystem&&<form action={archiveExpenseCategoryAction.bind(null,goalId,category.id)}><ConfirmSubmitButton className="danger-text-button" message={tr(locale,`Архивировать категорию «${category.name}»? Старые расходы сохранят эту категорию, но для новых операций она больше предлагаться не будет.`,`Archive “${category.name}”? Existing expenses keep the category but it will no longer be offered for new transactions.`)}>{tr(locale,"Архивировать категорию","Archive category")}</ConfirmSubmitButton></form>}</div></>}</div></details>;
}
